@startuml
class "Window" as C_0008871575618986871683
class C_0008871575618986871683 {
+Window(const std::string & window_name) : void
+~Window() : void
..
#draw() : void
+init() : bool
#init_glfw() : bool
#init_gui() : bool
#render() : void
+run() : void
__
#height_ : int
#name_ : std::string
#width_ : int
#window_ : GLFWwindow *
}
abstract "Shape" as C_0007080987761836185060
abstract C_0007080987761836185060 {
+~Shape() constexpr = default : void
..
+add_control_point(float x, float y) : void
{abstract} +draw(const Config & config) const = 0 : void
{abstract} +update(float x, float y) = 0 : void
__
}
class "Shape::Config" as C_0007933054238878135100
class C_0007933054238878135100 {
__
+bias : float[2]
+line_color : unsigned char[4]
+line_thickness : float
}
abstract "Widget" as C_0017184784915024955243
abstract C_0017184784915024955243 {
+Widget(const std::string & label) : void
+~Widget() constexpr = default : void
..
{abstract} +draw() = 0 : void
__
#label_ : std::string
}
class "Canvas" as C_0010143599884954815735
class C_0010143599884954815735 {
+clear_shape_list() : void
+draw() : void
-draw_background() : void
-draw_shapes() : void
-mouse_click_event() : void
-mouse_move_event() : void
-mouse_pos_in_canvas() const : ImVec2
-mouse_release_event() : void
-mouse_right_click_event() : void
+set_attributes(const ImVec2 & min, const ImVec2 & size) : void
+set_default() : void
+set_ellipse() : void
+set_line() : void
+set_polygon() : void
+set_rect() : void
+show_background(bool flag) : void
__
-background_color_ : ImU32
-border_color_ : ImU32
-canvas_max_ : ImVec2
-canvas_min_ : ImVec2
-canvas_minimal_size_ : ImVec2
-canvas_size_ : ImVec2
-current_shape_ : std::shared_ptr<Shape>
-draw_status_ : bool
-end_point_ : ImVec2
-is_active_ : bool
-is_hovered_ : bool
-shape_list_ : std::vector<std::shared_ptr<Shape>>
-shape_type_ : ShapeType
-show_background_ : bool
-start_point_ : ImVec2
}
enum "Canvas::ShapeType" as C_0012239519789625349070
enum C_0012239519789625349070 {
kDefault
kLine
kRect
kEllipse
kPolygon
}
class "MiniDraw" as C_0016505036820764618062
class C_0016505036820764618062 {
+MiniDraw(const std::string & window_name) : void
+~MiniDraw() : void
..
+draw() : void
-draw_canvas() : void
__
-flag_show_canvas_view_ : bool
-p_canvas_ : std::shared_ptr<Canvas>
}
class "Ellipse" as C_0000967933873543071895
class C_0000967933873543071895 {
+Ellipse() = default : void
+Ellipse(float start_point_x, float start_point_y, float end_point_x, float end_point_y) : void
+~Ellipse() constexpr = default : void
..
+draw(const Config & config) const : void
+update(float x, float y) : void
__
-center_x_ : float
-center_y_ : float
-radius_x_ : float
-radius_y_ : float
}
class "Line" as C_0018444896120262260081
class C_0018444896120262260081 {
+Line() = default : void
+Line(float start_point_x, float start_point_y, float end_point_x, float end_point_y) : void
+~Line() constexpr = default : void
..
+draw(const Config & config) const : void
+update(float x, float y) : void
__
-end_point_x_ : float
-end_point_y_ : float
-start_point_x_ : float
-start_point_y_ : float
}
class "Polygon" as C_0000313255549101030507
class C_0000313255549101030507 {
+Polygon() = default : void
+Polygon(float x, float y) : void
+Polygon(std::vector<float> x_list, std::vector<float> y_list) : void
+~Polygon() constexpr = default : void
..
+add_control_point(float x, float y) : void
+close() : void
+draw(const Config & config) const : void
+point_count() const : size_t
+update(float x, float y) : void
__
-is_finished_ : bool
-preview_x_ : float
-preview_y_ : float
-x_list_ : std::vector<float>
-y_list_ : std::vector<float>
}
class "Rect" as C_0008233609096235910285
class C_0008233609096235910285 {
+Rect() = default : void
+Rect(float start_point_x, float start_point_y, float end_point_x, float end_point_y) : void
+~Rect() constexpr = default : void
..
+draw(const Config & config) const : void
+update(float x, float y) : void
__
-end_point_x_ : float
-end_point_y_ : float
-start_point_x_ : float
-start_point_y_ : float
}
C_0007080987761836185060 ..> C_0007933054238878135100
C_0007933054238878135100 --+ C_0007080987761836185060
C_0010143599884954815735 o-- C_0012239519789625349070 : -shape_type_
C_0010143599884954815735 --> C_0007080987761836185060 : -current_shape_
C_0010143599884954815735 o-- C_0007080987761836185060 : -shape_list_
C_0017184784915024955243 <|-- C_0010143599884954815735
C_0012239519789625349070 --+ C_0010143599884954815735
C_0016505036820764618062 --> C_0010143599884954815735 : -p_canvas_
C_0008871575618986871683 <|-- C_0016505036820764618062
C_0000967933873543071895 ..> C_0007933054238878135100
C_0007080987761836185060 <|-- C_0000967933873543071895
C_0018444896120262260081 ..> C_0007933054238878135100
C_0007080987761836185060 <|-- C_0018444896120262260081
C_0000313255549101030507 ..> C_0007933054238878135100
C_0007080987761836185060 <|-- C_0000313255549101030507
C_0008233609096235910285 ..> C_0007933054238878135100
C_0007080987761836185060 <|-- C_0008233609096235910285

'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
